# Generated by Django 2.2.5 on 2019-09-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickers',
        ),
    ]
